### ISSUE TITLE
28BY stepper version

### ISSUE THREAD

**Issue by jvegaf** [bqlabs/MicroStage#1]
Hi, I found 2 versions of 28BY steppers motors, one of 5v and other of 12v, what I have to get?

Thanks

**Comment by owenlab** [comment]
Hi, it depend on your controller board, I means, if you will use a ramps you can chose the 12V version or if tou want to use a simple H-Bridge the optimal chose is the 5V version.
At the moment I'm focused on the Nema version, using a CNC shield, but I'm also drawed a board that permit to chose the power voltage and I will use it to move the 28BY version
